"""Add MCQ fields to Problem model

Revision ID: 4b3b11747430
Revises: 
Create Date: 2026-05-01 16:11:11.617769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b3b11747430'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('question_type', sa.String(length=50), nullable=True))
    op.add_column('problems', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('problems', sa.Column('correct_option', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'correct_option')
    op.drop_column('problems', 'options')
    op.drop_column('problems', 'question_type')
    # ### end Alembic commands ###
