"""apply unified question architecture

Revision ID: eae03169a97c
Revises: 95a573d0a885
Create Date: 2026-05-05 11:27:38.426757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eae03169a97c'
down_revision: Union[str, None] = '95a573d0a885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badges', 'icon_url')
    op.add_column('problems', sa.Column('options', sa.JSON(), nullable=True))
    op.add_column('problems', sa.Column('correct_option_index', sa.Integer(), nullable=True))
    op.add_column('problems', sa.Column('starter_files', sa.JSON(), nullable=True))
    op.add_column('problems', sa.Column('entry_point', sa.String(length=255), nullable=True))
    op.add_column('problems', sa.Column('test_harness', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('database_schema', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_problems_external_task'), table_name='problems')
    op.drop_index(op.f('ix_problems_source_dataset'), table_name='problems')
    op.drop_index(op.f('ix_problems_source_name'), table_name='problems')
    op.drop_column('problems', 'external_task_id')
    op.drop_column('problems', 'type_data')
    op.drop_column('problems', 'source_url')
    op.drop_column('problems', 'source_name')
    op.drop_column('problems', 'source_dataset')
    op.drop_column('skills', 'icon_url')
    op.drop_column('submissions', 'ai_feedback_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('ai_feedback_status', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('skills', sa.Column('icon_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('source_dataset', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('source_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('source_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('type_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('external_task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_problems_source_name'), 'problems', ['source_name'], unique=False)
    op.create_index(op.f('ix_problems_source_dataset'), 'problems', ['source_dataset'], unique=False)
    op.create_index(op.f('ix_problems_external_task'), 'problems', ['external_task_id'], unique=False)
    op.drop_column('problems', 'database_schema')
    op.drop_column('problems', 'test_harness')
    op.drop_column('problems', 'entry_point')
    op.drop_column('problems', 'starter_files')
    op.drop_column('problems', 'correct_option_index')
    op.drop_column('problems', 'options')
    op.add_column('badges', sa.Column('icon_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
